In [1]:
import pandas as pd


In [2]:
%store -r trump_tweets

In [3]:
%store -r biden_tweets

In [4]:
%store -r election2020_tweets

In [5]:
all_tweets = pd.concat([trump_tweets, biden_tweets, election2020_tweets], ignore_index = True )

In [7]:
#check how many tweets are duplicated
all_tweets.duplicated(subset = ['tweet']).value_counts()

False    51915
True      5154
dtype: int64

**The total number of collected tweets is 51915+5154 = 57069**

In [8]:
#delete identical tweets
all_tweets.drop_duplicates('tweet','first', inplace = True)

/var/folders/qm/j2nyw_6j7272_3cq86kpw75r0000gn/T/ipykernel_961/1800528475.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop_duplicates except for the argument 'subset' will be keyword-only
  all_tweets.drop_duplicates('tweet','first', inplace = True)


In [9]:
len(all_tweets)

51915

In [10]:
from nltk.corpus import stopwords

In [11]:
#remove stopwords from 's_token' column
stops = set(stopwords.words("english")) #stopwords

In [12]:
def RemoveStopwords(x):
    a = []
    for word in x:
        if word not in stops:
            a.append(word)
            
    return a

In [13]:

all_tweets['token'] = all_tweets['s_token'].map(lambda x: RemoveStopwords(x))
#w for w in corpus if not w in stops

In [18]:
all_tweets.head()

index                 date  \
0    0.0  2020-10-24 00:59:59   
1    1.0  2020-10-24 00:59:59   
2    2.0  2020-10-24 00:59:59   
3    3.0  2020-10-24 00:59:59   
4    4.0  2020-10-24 00:59:59   

                                               tweet language  \
0   chikooslim i was thinking that since it was t...       en   
1  he s been saying that for four years   alllies...       en   
2  incredibly thought provoking article  make sur...       en   
3   diadexxus  tugrik it was  but that s not sayi...       en   
4  don lemon meltdown over black trump support   ...       en   

           user_id_str         username  \
0             18491914         slattfri   
1             46384399  francesmiddlet2   
2           2902130034         mfly1971   
3             15608869      Ryu_Raccoon   
4  1216233063115395072       MackmanAce   

                                                docs  \
0  ( , chikooslim, i, was, thinking, that, since,...   
1  (he, s, been, saying, that, for, four, years, ...   
2  (incredibly, thought, provoking, article,  , m...   
3  ( , diadexxus,  , tugrik, it, was,  , but, tha...   
4  (don, lemon, meltdown, over, black, trump, sup...   

                                       lemmatization  \
0    chikooslim I be think that since it be the d...   
1  he s be say that for four year    alllie   tru...   
2  incredibly think provoke article   make sure y...   
3    diadexxus   tugrik it be   but that s not sa...   
4  don lemon meltdown over black trump support   ...   

                                             s_token  \
0  [chikooslim, I, be, think, that, since, it, be...   
1  [he, s, be, say, that, for, four, year, alllie...   
2  [incredibly, think, provoke, article, make, su...   
3  [diadexxus, tugrik, it, be, but, that, s, not,...   
4  [don, lemon, meltdown, over, black, trump, sup...   

                                               token  
0  [chikooslim, I, think, since, daughter, refuse...  
1  [say, four, year, alllie, trumplie, time, narc...  
2  [incredibly, think, provoke, article, make, su...  
3  [diadexxus, tugrik, say, much, hard, get, bad,...  
4  [lemon, meltdown, black, trump, support, via, ...

In [85]:
%store all_tweets

Stored 'all_tweets' (DataFrame)
